### ISSUE TITLE
Banning is broken... Again...

### ISSUE THREAD

**Issue by Wild1145** [Superior-Development/IcarusMod#201]
> [15:17:49] [Server thread/INFO]: Wild1145 issued server command: /ban wwwwario64 Destroying builds on the server.
> [15:17:49] [Server thread/ERROR]: null
> java.lang.reflect.InvocationTargetException
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_77]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_77]
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_77]
> 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_77]
> 	at com.superiornetworks.pegasus.commands.ICM_BlankCommand.onCommand(ICM_BlankCommand.java:36) [PagasusMod.jar:?]
> 	at com.superiornetworks.pegasus.commands.ICM_Command$ReflectCommand.execute(ICM_Command.java:194) [PagasusMod.jar:?]
> 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot.jar:git-Spigot-c3e4052-1953f52]
> 	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:646) [spigot.jar:git-Spigot-c3e4052-1953f52]
> 	at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1351) [spigot.jar:git-Spigot-c3e4052-1953f52]
> 	at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1186) [spigot.jar:git-Spigot-c3e4052-1953f52]
> 	at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-c3e4052-1953f52]
> 	at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-c3e4052-1953f52]
> 	at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-c3e4052-1953f52]
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_77]
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_77]
> 	at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot.jar:git-Spigot-c3e4052-1953f52]
> 	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:733) [spigot.jar:git-Spigot-c3e4052-1953f52]
> 	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-c3e4052-1953f52]
> 	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:672) [spigot.jar:git-Spigot-c3e4052-1953f52]
> 	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:571) [spigot.jar:git-Spigot-c3e4052-1953f52]
> 	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
> Caused by: java.lang.NullPointerException
> 	at com.superiornetworks.pegasus.PM_Bans.isBanned(PM_Bans.java:107) ~[?:?]
> 	at com.superiornetworks.pegasus.commands.Command_ban.onCommand(Command_ban.java:44) ~[?:?]
> 	... 21 more

**Comment by Wild1145** [comment]
I should also add that the player was offline at the time.
