### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by Hockeyfan360** [Superior-Development/IcarusMod#22]
Basically, I get this error every time I try to load the plugin. I have compiled the plugin with craftbukkit1.8 and BukkitLib1.3.

[17:32:01] [Server thread/INFO]: [IcarusMod] Enabling IcarusMod v0.0.0
[17:32:01] [Server thread/ERROR]: Error occurred while enabling IcarusMod v0.0.0 (Is it up to date?)
java.lang.NullPointerException
    at com.superiornetworks.icarus.IcarusMod.onEnable(IcarusMod.java:40) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[craftbukkit.jar:git-Bukkit-"24557bc"]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:325) [craftbukkit.jar:git-Bukkit-"24557bc"]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [craftbukkit.jar:git-Bukkit-"24557bc"]
    at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:338) [craftbukkit.jar:git-Bukkit-"24557bc"]
    at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:311) [craftbukkit.jar:git-Bukkit-"24557bc"]
    at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:392) [craftbukkit.jar:git-Bukkit-"24557bc"]
    at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:360) [craftbukkit.jar:git-Bukkit-"24557bc"]
    at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:315) [craftbukkit.jar:git-Bukkit-"24557bc"]
    at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:190) [craftbukkit.jar:git-Bukkit-"24557bc"]
    at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:475) [craftbukkit.jar:git-Bukkit-"24557bc"]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_25]

**Comment by Wild1145** [comment]
I cant say as I have tried to actually run the plugin yet... I will take a look in to this and see if there is a simple explanation.

**Comment by Wild1145** [comment]
I think the best way to easily resolve this is to switch from the current way of logging and use TFM's logging system...

**Comment by Hockeyfan360** [comment]
It has (from my knowledge to this point) nothing to do with the logger. I completely removed the logger from the class.

**Comment by Hockeyfan360** [comment]
I am still getting errors. I will be creating a completely new main class. I will be making the old main class notes, that way we can easily revert it back to its previous state.

EDIT: The new class works. Since I am replacing the whole main class, I will be seeking your permission before committing.

**Comment by Hockeyfan360** [comment]
I have no errors with startup. I need to know why commands aren't working. I will be posting a pull request so that you can see what I am talking about.

**Comment by Wild1145** [comment]
@Hockeyfan360 Could you push the code either to a PR or create a BLEEDING branch so that myself and the other developers can take a look and see if we can identify the issue please.

**Comment by Hockeyfan360** [comment]
@Wild1145 Done.
