### ISSUE TITLE
Cleanup Main Plugin File

### ISSUE THREAD

**Issue by Fyrsta** [Superior-Development/IcarusMod#33]
There's quite a few things that could be done to cleanup the main plugin file.

For example, https://github.com/Superior-Development/IcarusMod/blob/master/src/com/superiornetworks/icarus/IcarusMod.java#L47 doesn't need to be there at all since line 46 does the same thing.

And https://github.com/Superior-Development/IcarusMod/blob/master/src/com/superiornetworks/icarus/IcarusMod.java#L53 could be simplified with the register system in BukkitLib. You just need to do register(listener) and it'll do it for you. In the way you've done it currently, you could just do register(new PlayerListener(plugin)) and that'll be it.

Also, while nitpicky, everything in the config file should be lowercase (for variable names), so instead of Hostname it should be hostname.

Not that important, but it's good to have clean code.

**Comment by Wild1145** [comment]
https://github.com/Superior-Development/IcarusMod/blob/master/src/com/superiornetworks/icarus/IcarusMod.java#L47  was something @Hockeyfan360 added before he knew how the command loading worked, thats something I was aware of myself and was planning to clean up in a later commit. 

I was not aware of the BukkitLib listener setup, thats something that would be good to switch to obviously if it is keeping the code cleaner. 

I will also make the appropriate config changes shortly, I was not fully aware of the standards for the way the configuration file should have been written out.

**Comment by Wild1145** [comment]
@WickedGamingUK For listener registering, when I look at some of the BukkitLib example projects, Is see:

``` Java
plugin.getServer().getPluginManager().registerEvents(new BlockListener(plugin), plugin);
```

as an example. While all on one line, that looks far less clean having loads of them. Unless there is a different way to load the listeners that I didnt see...

**Comment by Fyrsta** [comment]
@Wild1145 Using BukkitLib is a good way. However, feel free to try something I've wrote in TranxCraft (not tested, so it may not work):

```
Reflections listeners = new Reflections(PlayerListener.class.getPackage());

Set<Class<? extends Listener>> listenerSet = listeners.getSubTypesOf(Listener.class);

for (Class<? extends Listener> listener : listenerSet) {
    register(listener);
}
```

You'll need https://code.google.com/p/reflections/ for it to work but it _should_ allow you to dynamically register all listeners in the same package.

**Comment by Wild1145** [comment]
@WickedGamingUK Do you just build Reflections in to the plugin the same as BukkitLib?

**Comment by Fyrsta** [comment]
@Wild1145 Most likely.

**Comment by Fyrsta** [comment]
@Wild1145 Does it work?

**Comment by Wild1145** [comment]
@WickedGamingUK It seems that the code does, but I am having some problems actually building the dependency in to the plugin. I need to play around with it a bit more, so will do so later.

**Comment by Fyrsta** [comment]
@Wild1145 Just put it in the build.xml file like it does for BukkitLib.

**Comment by Wild1145** [comment]
@WickedGamingUK I did and it fixed one error, not the next. I need to play around a bit and find what the error is exactly pointing to and resolve that.

**Comment by Fyrsta** [comment]
@Wild1145 Alright, it should work but play around with it. It may need other dependancies.

**Comment by Wild1145** [comment]
I am working on this and a few other bits on the cleanup branch. https://github.com/Superior-Development/IcarusMod/tree/Cleanup

**Comment by Wild1145** [comment]
The good news is that I have tested it and the Jar is having reflections build in. The bad thing is that I get this error.

```
[00:15:38] [Server thread/ERROR]: Error occurred while enabling IcarusMod v0.0.0 (Is it up to date?)
java.lang.NoClassDefFoundError: javassist/bytecode/ClassFile
    at org.reflections.adapters.JavassistAdapter.getOfCreateClassObject(JavassistAdapter.java:100) ~[?:?]
    at org.reflections.adapters.JavassistAdapter.getOfCreateClassObject(JavassistAdapter.java:24) ~[?:?]
    at org.reflections.scanners.AbstractScanner.scan(AbstractScanner.java:30) ~[?:?]
    at org.reflections.Reflections.scan(Reflections.java:238) ~[?:?]
    at org.reflections.Reflections.scan(Reflections.java:204) ~[?:?]
    at org.reflections.Reflections.<init>(Reflections.java:129) ~[?:?]
    at org.reflections.Reflections.<init>(Reflections.java:170) ~[?:?]
    at com.superiornetworks.icarus.IcarusMod.onEnable(IcarusMod.java:58) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[server.jar:git-Spigot-b8f6402-a646500]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [server.jar:git-Spigot-b8f6402-a646500]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [server.jar:git-Spigot-b8f6402-a646500]
    at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:352) [server.jar:git-Spigot-b8f6402-a646500]
    at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:313) [server.jar:git-Spigot-b8f6402-a646500]
    at org.bukkit.craftbukkit.v1_8_R1.CraftServer.reload(CraftServer.java:741) [server.jar:git-Spigot-b8f6402-a646500]
    at org.bukkit.Bukkit.reload(Bukkit.java:534) [server.jar:git-Spigot-b8f6402-a646500]
    at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:23) [server.jar:git-Spigot-b8f6402-a646500]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) [server.jar:git-Spigot-b8f6402-a646500]
    at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:642) [server.jar:git-Spigot-b8f6402-a646500]
    at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1105) [server.jar:git-Spigot-b8f6402-a646500]
    at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:940) [server.jar:git-Spigot-b8f6402-a646500]
    at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26) [server.jar:git-Spigot-b8f6402-a646500]
    at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53) [server.jar:git-Spigot-b8f6402-a646500]
    at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [server.jar:git-Spigot-b8f6402-a646500]
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_20]
    at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_20]
    at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:683) [server.jar:git-Spigot-b8f6402-a646500]
    at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [server.jar:git-Spigot-b8f6402-a646500]
    at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [server.jar:git-Spigot-b8f6402-a646500]
    at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [server.jar:git-Spigot-b8f6402-a646500]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_20]
Caused by: java.lang.ClassNotFoundException: javassist.bytecode.ClassFile
    at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_20]
    at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_20]
    at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_20]
    at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_20]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[server.jar:git-Spigot-b8f6402-a646500]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[server.jar:git-Spigot-b8f6402-a646500]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_20]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_20]
    ... 30 more
```

I am not 100% sure even what is happening other than a dependency / package / file is missing... @WickedGamingUK your help would be useful here.

**Comment by Fyrsta** [comment]
@Wild1145 A required dependency isn't found. That's what that error means.

**Comment by Wild1145** [comment]
@WickedGamingUK Thats the thing... The dependency is built in, I even de-compiled the plugin to check... Evidently more dependencies are required...

**Comment by Fyrsta** [comment]
@Wild1145 Yeah, probably best to find out what all of the needed dependencies are and then create a jar where it has all of the dependencies built in for simplistically.

**Comment by Wild1145** [comment]
Upon a deeper investigation, there appears to be dependencies within the dependencies... Thats why this is causing problems... There will be no easy way to do this without building about 20 different dependencies into one plugin, and thats going to get messy as I just tried...

**Comment by Fyrsta** [comment]
I'll try building it with maven and give you a jar with all of the required dependencies.
