### ISSUE TITLE
MySQL Failing to enable

### ISSUE THREAD

**Issue by Wild1145** [Superior-Development/IcarusMod#61]
MySQL is failing to read the password in the config.yml and as such will not actually start up. Error is as follows:

[14:44:10 INFO]: [IcarusMod] Enabling IcarusMod v0.7
[14:44:10 ERROR]: [IcarusMod] Could not connect to MySQL server! because: Access denied for user ''@'localhost' (using password: NO)
[14:44:10 ERROR]: Error occurred while enabling IcarusMod v0.7 (Is it up to date?)
java.lang.NullPointerException
        at com.superiornetworks.icarus.ICM_SqlHandler.generateTables(ICM_SqlHandler.java:25) ~[?:?]
        at com.superiornetworks.icarus.IcarusMod.onEnable(IcarusMod.java:86) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigotserver.jar:git-Spigot-dbe012b-61ef214]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [spigotserver.jar:git-Spigot-dbe012b-61ef214]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigotserver.jar:git-Spigot-dbe012b-61ef214]
        at org.bukkit.craftbukkit.v1_8_R2.CraftServer.loadPlugin(CraftServer.java:356) [spigotserver.jar:git-Spigot-dbe012b-61ef214]
        at org.bukkit.craftbukkit.v1_8_R2.CraftServer.enablePlugins(CraftServer.java:316) [spigotserver.jar:git-Spigot-dbe012b-61ef214]
        at org.bukkit.craftbukkit.v1_8_R2.CraftServer.reload(CraftServer.java:746) [spigotserver.jar:git-Spigot-dbe012b-61ef214]
        at org.bukkit.Bukkit.reload(Bukkit.java:534) [spigotserver.jar:git-Spigot-dbe012b-61ef214]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25) [spigotserver.jar:git-Spigot-dbe012b-61ef214]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigotserver.jar:git-Spigot-dbe012b-61ef214]
        at org.bukkit.craftbukkit.v1_8_R2.CraftServer.dispatchCommand(CraftServer.java:646) [spigotserver.jar:git-Spigot-dbe012b-61ef214]
        at org.bukkit.craftbukkit.v1_8_R2.CraftServer.dispatchServerCommand(CraftServer.java:632) [spigotserver.jar:git-Spigot-dbe012b-61ef214]
        at net.minecraft.server.v1_8_R2.DedicatedServer.aN(DedicatedServer.java:405) [spigotserver.jar:git-Spigot-dbe012b-61ef214]
        at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:369) [spigotserver.jar:git-Spigot-dbe012b-61ef214]
        at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigotserver.jar:git-Spigot-dbe012b-61ef214]
        at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigotserver.jar:git-Spigot-dbe012b-61ef214]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]

**Comment by Wild1145** [comment]
Just done some looking, and it appears that its completely ignoring the config.yml file... So Thats why this isnt working. @CameronRedmore
