### ISSUE TITLE
MySQL Error

### ISSUE THREAD

**Issue by Wild1145** [Superior-Development/IcarusMod#62]
Not sure what this one is ( @CameronRedmore  @WickedGamingUK )

[15:03:02 INFO]: [IcarusMod] Enabling IcarusMod v0.7
[15:03:02 ERROR]: [IcarusMod] Could not connect to MySQL server! because: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
[15:03:02 ERROR]: Error occurred while enabling IcarusMod v0.7 (Is it up to date?)
java.lang.NullPointerException
        at com.superiornetworks.icarus.ICM_SqlHandler.generateTables(ICM_SqlHandler.java:25) ~[?:?]
        at com.superiornetworks.icarus.IcarusMod.onEnable(IcarusMod.java:86) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigotserver.jar:git-Spigot-dbe012b-61ef214]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [spigotserver.jar:git-Spigot-dbe012b-61ef214]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigotserver.jar:git-Spigot-dbe012b-61ef214]
        at org.bukkit.craftbukkit.v1_8_R2.CraftServer.loadPlugin(CraftServer.java:356) [spigotserver.jar:git-Spigot-dbe012b-61ef214]
        at org.bukkit.craftbukkit.v1_8_R2.CraftServer.enablePlugins(CraftServer.java:316) [spigotserver.jar:git-Spigot-dbe012b-61ef214]
        at org.bukkit.craftbukkit.v1_8_R2.CraftServer.reload(CraftServer.java:746) [spigotserver.jar:git-Spigot-dbe012b-61ef214]
        at org.bukkit.Bukkit.reload(Bukkit.java:534) [spigotserver.jar:git-Spigot-dbe012b-61ef214]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25) [spigotserver.jar:git-Spigot-dbe012b-61ef214]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigotserver.jar:git-Spigot-dbe012b-61ef214]
        at org.bukkit.craftbukkit.v1_8_R2.CraftServer.dispatchCommand(CraftServer.java:646) [spigotserver.jar:git-Spigot-dbe012b-61ef214]
        at net.minecraft.server.v1_8_R2.PlayerConnection.handleCommand(PlayerConnection.java:1133) [spigotserver.jar:git-Spigot-dbe012b-61ef214]
        at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:968) [spigotserver.jar:git-Spigot-dbe012b-61ef214]
        at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigotserver.jar:git-Spigot-dbe012b-61ef214]
        at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigotserver.jar:git-Spigot-dbe012b-61ef214]
        at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigotserver.jar:git-Spigot-dbe012b-61ef214]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_25]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_25]
        at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60) [spigotserver.jar:git-Spigot-dbe012b-61ef214]
        at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:710) [spigotserver.jar:git-Spigot-dbe012b-61ef214]
        at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigotserver.jar:git-Spigot-dbe012b-61ef214]
        at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigotserver.jar:git-Spigot-dbe012b-61ef214]
        at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigotserver.jar:git-Spigot-dbe012b-61ef214]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]

**Comment by Wild1145** [comment]
@Superior-Development/superior-freedom-network-pull-push

**Comment by Fyrsta** [comment]
See http://stackoverflow.com/questions/2121829/com-mysql-jdbc-exceptions-jdbc4-communicationsexceptioncommunications-link-fail
