### ISSUE TITLE
Table Generation Not Working

### ISSUE THREAD

**Issue by Wild1145** [Superior-Development/IcarusMod#71]
[14:41:54] [Server thread/INFO]: [IcarusMod] Enabling IcarusMod v0.7
[14:41:54] [Server thread/ERROR]: [IcarusMod] Could not connect to MySQL server! because: Cannot load connection class because of underlying exception: 'java.lang.NumberFormatException: For input string: "null"'.
[14:41:54] [Server thread/ERROR]: Error occurred while enabling IcarusMod v0.7 (Is it up to date?)
java.lang.NullPointerException
    at com.superiornetworks.icarus.ICM_SqlHandler.generateTables(ICM_SqlHandler.java:57) ~[?:?]
    at com.superiornetworks.icarus.IcarusMod.onEnable(IcarusMod.java:96) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigotserver.jar:git-Spigot-b8f6402-a646500]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [spigotserver.jar:git-Spigot-b8f6402-a646500]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigotserver.jar:git-Spigot-b8f6402-a646500]
    at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:352) [spigotserver.jar:git-Spigot-b8f6402-a646500]
    at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:313) [spigotserver.jar:git-Spigot-b8f6402-a646500]
    at org.bukkit.craftbukkit.v1_8_R1.CraftServer.reload(CraftServer.java:741) [spigotserver.jar:git-Spigot-b8f6402-a646500]
    at org.bukkit.Bukkit.reload(Bukkit.java:534) [spigotserver.jar:git-Spigot-b8f6402-a646500]
    at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:23) [spigotserver.jar:git-Spigot-b8f6402-a646500]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) [spigotserver.jar:git-Spigot-b8f6402-a646500]
    at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:642) [spigotserver.jar:git-Spigot-b8f6402-a646500]
    at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchServerCommand(CraftServer.java:628) [spigotserver.jar:git-Spigot-b8f6402-a646500]
    at net.minecraft.server.v1_8_R1.DedicatedServer.aM(DedicatedServer.java:353) [spigotserver.jar:git-Spigot-b8f6402-a646500]
    at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:317) [spigotserver.jar:git-Spigot-b8f6402-a646500]
    at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [spigotserver.jar:git-Spigot-b8f6402-a646500]
    at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [spigotserver.jar:git-Spigot-b8f6402-a646500]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]

**Comment by Wild1145** [comment]
It would appear that the reasons for this error is that the config options for the MySQL Database details are being removed on a reload, meaning the plugin has nothing to connect to.

**Comment by CameronRedmore** [comment]
Fixed in the latest push.
