### ISSUE TITLE
Imposter Problems

### ISSUE THREAD

**Issue by Wild1145** [Superior-Development/IcarusMod#72]
[13:41:20 INFO]: Wild1145 issued server command: /p
[13:41:20 ERROR](null): Could not pass event PlayerCommandPreprocessEvent to IcarusMod v1.0
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigotserver.jar:git-Spigot-b8f6402-a646500]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigotserver.jar:git-Spigot-b8f6402-a646500]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigotserver.jar:git-Spigot-b8f6402-a646500]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigotserver.jar:git-Spigot-b8f6402-a646500]
        at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1097) [spigotserver.jar:git-Spigot-b8f6402-a646500]
        at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:940) [spigotserver.jar:git-Spigot-b8f6402-a646500]
        at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26) [spigotserver.jar:git-Spigot-b8f6402-a646500]
        at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53) [spigotserver.jar:git-Spigot-b8f6402-a646500]
        at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [spigotserver.jar:git-Spigot-b8f6402-a646500]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_25]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_25]
        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:683) [spigotserver.jar:git-Spigot-b8f6402-a646500]
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigotserver.jar:git-Spigot-b8f6402-a646500]
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [spigotserver.jar:git-Spigot-b8f6402-a646500]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [spigotserver.jar:git-Spigot-b8f6402-a646500]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
Caused by: java.lang.NullPointerException
        at com.superiornetworks.icarus.ICM_Rank.getRank(ICM_Rank.java:57) ~[?:?]
        at com.superiornetworks.icarus.modules.CommandSpyModule.onCommandPreprocess(CommandSpyModule.java:39) ~[?:?]
        at com.superiornetworks.icarus.listeners.PlayerListener.onCommandPreprocess(PlayerListener.java:39) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
        at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[spigotserver.jar:git-Spigot-b8f6402-a646500]
        ... 15 more
[13:41:20 INFO]: [PREPROCESS_COMMAND] Wild1145(Wild1145): /p

org.bukkit.command.CommandException: Unhandled exception executing 'p' in com.superiornetworks.icarus.commands.ICM_Command$ReflectCommand(p)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:188) ~[spigotserver.jar:git-Spigot-b8f6402-a646500]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:642) ~[spigotserver.jar:git-Spigot-b8f6402-a646500]
        at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1105) [spigotserver.jar:git-Spigot-b8f6402-a646500]
        at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:940) [spigotserver.jar:git-Spigot-b8f6402-a646500]
        at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26) [spigotserver.jar:git-Spigot-b8f6402-a646500]
        at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53) [spigotserver.jar:git-Spigot-b8f6402-a646500]
        at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [spigotserver.jar:git-Spigot-b8f6402-a646500]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_25]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_25]
        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:683) [spigotserver.jar:git-Spigot-b8f6402-a646500]
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigotserver.jar:git-Spigot-b8f6402-a646500]
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [spigotserver.jar:git-Spigot-b8f6402-a646500]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [spigotserver.jar:git-Spigot-b8f6402-a646500]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
Caused by: java.lang.NullPointerException
        at com.superiornetworks.icarus.ICM_Rank.getRank(ICM_Rank.java:57) ~[?:?]
        at com.superiornetworks.icarus.ICM_Rank.isRankOrHigher(ICM_Rank.java:36) ~[?:?]
        at com.superiornetworks.icarus.commands.ICM_Command$ReflectCommand.execute(ICM_Command.java:188) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[spigotserver.jar:git-Spigot-b8f6402-a646500]
        ... 13 more

**Comment by Wild1145** [comment]
Fixed when the tables were dropped and re-created.
